version: "3.8"

services:
  postgres:
    extends:
      file: ./services/postgres/docker-compose.yml
      service: postgres
    env_file:
      - ./services/postgres/.env

  redis:
    extends:
      file: ./services/redis/docker-compose.yml
      service: redis
    env_file:
      - ./services/redis/.env

  rabbitmq:
    extends:
      file: ./services/rabbitmq/docker-compose.yml
      service: rabbitmq
    env_file:
      - ./services/rabbitmq/.env

  litellm:
    extends:
      file: ./services/ai-service/docker-compose.yml
      service: litellm
    env_file:
      - ./services/ai-service/.env
    depends_on:
      redis:
        condition: service_healthy

networks:
  agentbuilder-network:
    driver: bridge
